name: hina_app
description: "Hina - Sua amiga IA fofa!"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.0
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  intl: ^0.20.2
  uuid: ^4.0.0
  shared_preferences: ^2.2.2
  google_generative_ai: ^0.2.2
  flutter_dotenv: ^5.1.0
  flutter_localizations:
    sdk: flutter
  flutter_gen: ^5.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  generate: true
  uses-material-design:  true
  assets:
        - .env
